# =============================================================================
# Fish-passage inputs snapshot — pull current parquet snapshots from template
# repo into this repo's data/snapshots/ so Fraser builds cleanly from `git
# clone` with no cross-repo runtime dependencies.
#
# Self-containment principle (#180 + the eDNA precedent in
# edna_inputs_snapshot.R):
#   Fraser must build from a fresh clone without reaching into other repos at
#   runtime. The fish-passage canonical wrangle (postgres -> parquet) lives in
#   `fish_passage_template_reporting/scripts/pg_load-fp.R` and writes
#   `data/snapshots/<table>.parquet` + `manifest.yaml` upstream. This script
#   copies those committed parquets here and writes a manifest capturing the
#   upstream commit SHA so the snapshot is traceable.
#
# Refresh procedure (when upstream updates):
#   1. In template repo:
#        - re-run scripts/pg_load-fp.R against the latest postgres state
#        - commit + push the refreshed parquets
#   2. In this repo:
#        - source('scripts/fp_inputs_snapshot.R')
#        - inspect data/fp_inputs_snapshot_manifest.txt diff (commit SHA +
#          timestamp moves; parquet diffs reflect actual data changes)
#        - commit the refreshed inputs
#
# Idempotent on no-change: if a parquet is byte-identical to upstream and the
# upstream commit hasn't moved, nothing is written.
# =============================================================================

UPSTREAM_REPO_LABEL <- "NewGraphEnvironment/fish_passage_template_reporting"
UPSTREAM_PATH       <- "~/Projects/repo/fish_passage_template_reporting"

# Files to snapshot (relative paths, identical in source + destination).
# Add more parquets as this report's consumer scope grows.
INPUTS <- c(
  "data/snapshots/fp_sites_tracking.parquet"
)

MANIFEST <- "data/fp_inputs_snapshot_manifest.txt"

up_path <- path.expand(UPSTREAM_PATH)
if (!dir.exists(up_path)) {
  stop("Upstream repo not found at ", UPSTREAM_PATH,
       ". Clone it locally before running this snapshot.")
}

up_sha <- system2("git", c("-C", up_path, "rev-parse", "HEAD"),
                  stdout = TRUE)[1]
up_dirty_lines <- system2("git", c("-C", up_path, "status", "--porcelain"),
                          stdout = TRUE)
up_dirty <- length(up_dirty_lines) > 0
if (up_dirty) {
  message(
    "WARNING: upstream working tree has uncommitted changes:\n  ",
    paste(up_dirty_lines, collapse = "\n  "),
    "\nSnapshot SHA `", up_sha, "` reflects last commit, not current files."
  )
}

prev_sha <- NA_character_
if (file.exists(MANIFEST)) {
  prev <- readLines(MANIFEST, warn = FALSE)
  m <- regmatches(prev, regexpr("(?<=^upstream_commit:\\s)[a-f0-9]+", prev,
                                perl = TRUE))
  if (length(m) > 0) prev_sha <- m[1]
}

copied  <- character(0)
skipped <- character(0)
for (rel in INPUTS) {
  src <- file.path(up_path, rel)
  dst <- rel
  if (!file.exists(src)) {
    stop("Upstream file missing: ", src,
         ". Re-run upstream pipeline before snapshotting.")
  }
  dst_dir <- dirname(dst)
  if (!dir.exists(dst_dir)) dir.create(dst_dir, recursive = TRUE)

  same <- file.exists(dst) &&
    identical(unname(tools::md5sum(src)), unname(tools::md5sum(dst)))
  if (same) {
    skipped <- c(skipped, rel)
  } else {
    file.copy(src, dst, overwrite = TRUE)
    copied <- c(copied, rel)
  }
}

manifest_changed <- length(copied) > 0 ||
  is.na(prev_sha) ||
  !identical(prev_sha, up_sha)

if (manifest_changed) {
  manifest_lines <- c(
    "# Fish-passage inputs snapshot manifest",
    paste0("# Generated by scripts/fp_inputs_snapshot.R on ",
           format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z")),
    "",
    paste0("upstream_repo:     ", UPSTREAM_REPO_LABEL),
    paste0("upstream_path:     ", UPSTREAM_PATH),
    paste0("upstream_commit:   ", up_sha),
    paste0("upstream_dirty:    ", tolower(as.character(up_dirty))),
    paste0("snapshotted_at:    ", format(Sys.time(), "%Y-%m-%dT%H:%M:%S%z")),
    "",
    "files:"
  )
  for (rel in INPUTS) {
    manifest_lines <- c(
      manifest_lines,
      sprintf("  - path: %s", rel),
      sprintf("    md5:  %s", unname(tools::md5sum(rel)))
    )
  }
  writeLines(manifest_lines, MANIFEST)
}

cat("=== Fish-passage inputs snapshot ===\n")
cat(sprintf("Upstream:  %s @ %s%s\n",
            UPSTREAM_REPO_LABEL, substr(up_sha, 1, 7),
            if (up_dirty) " (DIRTY)" else ""))
if (length(copied) > 0)
  cat(sprintf("Copied (%d):\n  - %s\n",
              length(copied), paste(copied, collapse = "\n  - ")))
if (length(skipped) > 0)
  cat(sprintf("Skipped, unchanged (%d):\n  - %s\n",
              length(skipped), paste(skipped, collapse = "\n  - ")))
cat(sprintf("Manifest:  %s%s\n",
            MANIFEST,
            if (manifest_changed) " (updated)" else " (unchanged)"))
